version: "3.8"

services:
  bot:
    build: .
    command: "python bot.py"
    volumes: [ .:/app ]
    env_file: [ .env ]
    restart: unless-stopped

    # ⬇ ждём, пока db пройдёт healthcheck
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped

    # shared_buffers = 64 MB  ➜ легко изменить: «128MB» и `docker compose up -d --build db`
    command: ["postgres", "-c", "shared_buffers=64MB"]

    environment:
      POSTGRES_USER: ${DB_USER:-bot_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bot_pass}
      POSTGRES_DB: ${DB_NAME:-farmbot}
      TZ: Europe/Moscow

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

    # ⬇ простейший healthcheck на pg_isready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-bot_user}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
